In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)

df = pd.read_csv('../data/raw/Zomato Dataset.csv')

df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  str
 1   Delivery_person_ID           45584 non-null  str
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  str
 9   Time_Orderd                  43853 non-null  str
 10  Time_Order_picked            45584 non-null  str
 11  Weather_conditions           44968 non-null  str
 12  Road_traffic_density         44983 non-null  str
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  str
 15  Type_of_vehicle              45584 non-null  str
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  str
 18  City                         44384 non-null  str
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 7.0 MB

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken (min)
count,43730.000000,43676.000000,45584.000000,45584.000000,45584.000000,45584.000000,45584.000000,44591.000000,45584.000000
mean,29.566911,4.633774,17.017948,70.229684,17.465480,70.844161,1.023385,0.744635,26.293963
std,5.815064,0.334744,8.185674,22.885575,7.335562,21.120578,0.839055,0.572510,9.384298
min,15.000000,1.000000,-30.905562,-88.366217,0.010000,0.010000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933284,73.170000,12.988453,73.280000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.551440,75.897963,18.633934,76.002574,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.728163,78.044095,22.785049,78.107044,2.000000,1.000000,32.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,3.000000,3.000000,54.000000

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [4]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [5]:
missing = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing = missing[missing["missing_count"] > 0] \
    .sort_values("missing_percentage", ascending=False)

missing

                         missing_count  missing_percentage
Delivery_person_Ratings           1908            4.185679
Delivery_person_Age               1854            4.067217
Time_Orderd                       1731            3.797385
City                              1200            2.632503
multiple_deliveries                993            2.178396
Weather_conditions                 616            1.351351
Road_traffic_density               601            1.318445
Festival                           228            0.500176

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.nunique().sort_values()

Festival                           2
City                               3
Road_traffic_density               4
Vehicle_condition                  4
Type_of_order                      4
multiple_deliveries                4
Type_of_vehicle                    4
Weather_conditions                 6
Delivery_person_Age               22
Delivery_person_Ratings           28
Order_Date                        44
Time_taken (min)                  45
Time_Orderd                      176
Time_Order_picked                193
Restaurant_longitude             518
Restaurant_latitude              657
Delivery_person_ID              1320
Delivery_location_latitude      4373
Delivery_location_longitude     4373
ID                             45584
dtype: int64

In [8]:
'''
Festival                           2
City                               3
Road_traffic_density               4
Vehicle_condition                  4
Type_of_order                      4
multiple_deliveries                4
Type_of_vehicle                    4
Weather_conditions                 6
'''

'\nFestival                           2\nCity                               3\nRoad_traffic_density               4\nVehicle_condition                  4\nType_of_order                      4\nmultiple_deliveries                4\nType_of_vehicle                    4\nWeather_conditions                 6\n'

In [9]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(10))

--- ID ---
ID
0xcdcd    1
0xd987    1
0x2784    1
0xc8b6    1
0xdb64    1
0x3af3    1
0x3aab    1
0x689b    1
0x6f67    1
0xc9cf    1
Name: count, dtype: int64

--- Delivery_person_ID ---
Delivery_person_ID
JAPRES11DEL02       67
PUNERES01DEL01      67
RANCHIRES02DEL01    66
VADRES11DEL02       66
JAPRES03DEL01       66
HYDRES04DEL02       66
VADRES08DEL02       66
SURRES11DEL01       65
INDORES08DEL02      65
VADRES11DEL01       65
Name: count, dtype: int64

--- Order_Date ---
Order_Date
15-03-2022    1192
03-04-2022    1178
13-03-2022    1169
26-03-2022    1165
24-03-2022    1162
09-03-2022    1159
05-04-2022    1156
05-03-2022    1154
07-03-2022    1153
03-03-2022    1150
Name: count, dtype: int64

--- Time_Orderd ---
Time_Orderd
NaN            1731
21:55           461
17:55           456
0.833333333     449
22:20           448
21:35           446
19:50           444
21:15           442
22:45           438
21:20           437
Name: count, dtype: int64

--- Time_Order_picked ---
Time_Order_picked
21:30    495
22:50    474
22:40    458
18:40    457
21:45    456
17:55    456
22:25    455
18:05    454
20:50    453
23:50    453
Name: count, dtype: int64

--- Weather_conditions ---
Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

--- Road_traffic_density ---
Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

--- Type_of_order ---
Type_of_order
Snack     11530
Meal      11456
Drinks    11321
Buffet    11277
Name: count, dtype: int64

--- Type_of_vehicle ---
Type_of_vehicle
motorcycle          26429
scooter             15273
electric_scooter     3814
bicycle                68
Name: count, dtype: int64

--- Festival ---
Festival
No     44460
Yes      896
NaN      228
Name: count, dtype: int64

--- City ---
City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

C:\Users\yumah\AppData\Local\Temp\ipykernel_27484\2775710678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [14]:
categorical_cols = [
    "Weather_conditions",
    "Road_traffic_density",
    "Vehicle_condition",
    "Type_of_order",
    "Type_of_vehicle",
    "multiple_deliveries",
    "Festival",
    "City"
]

for col in categorical_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts(dropna=False))

===== Weather_conditions =====
Weather_conditions
Fog           7653
Stormy        7584
Cloudy        7533
Sandstorms    7494
Windy         7422
Sunny         7282
NaN            616
Name: count, dtype: int64

===== Road_traffic_density =====
Road_traffic_density
Low       15476
Jam       14139
Medium    10945
High       4423
NaN         601
Name: count, dtype: int64

===== Vehicle_condition =====
Vehicle_condition
2    15031
1    15028
0    15005
3      520
Name: count, dtype: int64

===== Type_of_order =====
Type_of_order
Snack     11530
Meal      11456
Drinks    11321
Buffet    11277
Name: count, dtype: int64

===== Type_of_vehicle =====
Type_of_vehicle
motorcycle          26429
scooter             15273
electric_scooter     3814
bicycle                68
Name: count, dtype: int64

===== multiple_deliveries =====
multiple_deliveries
1.0    28151
0.0    14094
2.0     1985
NaN      993
3.0      361
Name: count, dtype: int64

===== Festival =====
Festival
No     44460
Yes      896
NaN      228
Name: count, dtype: int64

===== City =====
City
Metropolitian    34087
Urban            10133
NaN               1200
Semi-Urban         164
Name: count, dtype: int64

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Delivery_person_Age,43730.0,29.566911,5.815064,15.000000,25.000000,30.000000,35.000000,50.000000
Delivery_person_Ratings,43676.0,4.633774,0.334744,1.000000,4.500000,4.700000,4.900000,6.000000
Restaurant_latitude,45584.0,17.017948,8.185674,-30.905562,12.933284,18.551440,22.728163,30.914057
Restaurant_longitude,45584.0,70.229684,22.885575,-88.366217,73.170000,75.897963,78.044095,88.433452
Delivery_location_latitude,45584.0,17.465480,7.335562,0.010000,12.988453,18.633934,22.785049,31.054057
Delivery_location_longitude,45584.0,70.844161,21.120578,0.010000,73.280000,76.002574,78.107044,88.563452
Vehicle_condition,45584.0,1.023385,0.839055,0.000000,0.000000,1.000000,2.000000,3.000000
multiple_deliveries,44591.0,0.744635,0.572510,0.000000,0.000000,1.000000,1.000000,3.000000
Time_taken (min),45584.0,26.293963,9.384298,10.000000,19.000000,26.000000,32.000000,54.000000

In [16]:
for col in categorical_cols:
    print(f"\n===== {col} =====")
    print(df[col].dropna().map(repr).unique())

===== Weather_conditions =====
<StringArray>
[''Fog'', ''Stormy'', ''Sandstorms'', ''Windy'', ''Cloudy'', ''Sunny'']
Length: 6, dtype: str

===== Road_traffic_density =====
<StringArray>
[''Jam'', ''High'', ''Medium'', ''Low'']
Length: 4, dtype: str

===== Vehicle_condition =====
<StringArray>
['2', '1', '0', '3']
Length: 4, dtype: str

===== Type_of_order =====
<StringArray>
[''Snack'', ''Meal'', ''Drinks'', ''Buffet'']
Length: 4, dtype: str

===== Type_of_vehicle =====
<StringArray>
[''motorcycle'', ''scooter'', ''electric_scooter'', ''bicycle'']
Length: 4, dtype: str

===== multiple_deliveries =====
<StringArray>
['3.0', '1.0', '0.0', '2.0']
Length: 4, dtype: str

===== Festival =====
<StringArray>
[''No'', ''Yes'']
Length: 2, dtype: str

===== City =====
<StringArray>
[''Metropolitian'', ''Urban'', ''Semi-Urban'']
Length: 3, dtype: str

In [17]:
df['Delivery_person_Ratings'].value_counts().sort_index()

Delivery_person_Ratings
1.0      38
2.5      20
2.6      22
2.7      22
2.8      19
2.9      19
3.0       6
3.1      29
3.2      29
3.3      25
3.4      32
3.5     249
3.6     207
3.7     225
3.8     228
3.9     197
4.0    1077
4.1    1430
4.2    1418
4.3    1409
4.4    1360
4.5    3302
4.6    6938
4.7    7140
4.8    7146
4.9    7040
5.0    3996
6.0      53
Name: count, dtype: int64

In [18]:
df['Delivery_person_Age'].value_counts().sort_index()

Delivery_person_Age
15.0      38
20.0    2136
21.0    2153
22.0    2194
23.0    2086
24.0    2210
25.0    2174
26.0    2159
27.0    2150
28.0    2179
29.0    2191
30.0    2226
31.0    2120
32.0    2201
33.0    2186
34.0    2165
35.0    2261
36.0    2260
37.0    2226
38.0    2218
39.0    2144
50.0      53
Name: count, dtype: int64

In [19]:
print("Restaurant latitude <= 0:")
print((df["Restaurant_latitude"] <= 0).sum())

print("\nRestaurant longitude < 0:")
print((df["Restaurant_longitude"] < 0).sum())

print("\nDelivery latitude <= 0:")
print((df["Delivery_location_latitude"] <= 0).sum())

print("\nDelivery longitude <= 0:")
print((df["Delivery_location_longitude"] <= 0).sum())

Restaurant latitude <= 0:
4071

Restaurant longitude < 0:
162

Delivery latitude <= 0:
0

Delivery longitude <= 0:
0

In [20]:
print("Time_Orderd:")
print(df["Time_Orderd"].dropna().unique()[:30])

print("\nTime_Order_picked:")
print(df["Time_Order_picked"].dropna().unique()[:30])

Time_Orderd:
<StringArray>
[      '21:55',       '14:55',       '17:30',       '09:20',       '19:50',
       '20:25',       '20:30',       '20:40',       '21:15',       '20:20',
       '22:30',       '08:15',       '19:30',       '12:25',       '18:35',
       '20:35',       '23:20',       '21:20',       '23:35',       '22:35',
       '23:25',       '13:35',       '21:35',       '18:55',       '14:15',
 '0.458333333',       '09:45',       '08:40', '0.958333333',       '17:25']
Length: 30, dtype: str

Time_Order_picked:
<StringArray>
['22:10', '15:05', '17:40', '09:30', '20:05', '20:35', '15:10', '20:40',
 '20:50', '21:30', '20:25', '22:45', '08:30', '19:45', '12:30', '18:50',
 '23:30', '21:35', '23:45', '22:50', '22:40', '23:35', '13:40', '21:45',
 '19:10', '14:25', '11:10', '09:55', '08:55', '23:10']
Length: 30, dtype: str

In [21]:
print("Yuma")

Yuma