In [14]:
import pandas as pd
import numpy as np
from pathlib import Path

In [15]:
DATA_DIR = Path("../data")

df = pd.read_csv(DATA_DIR / "raw" / "Zomato Dataset.csv")

df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [16]:
df.info()
df.describe(include="all").T

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  str
 1   Delivery_person_ID           45584 non-null  str
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  str
 9   Time_Orderd                  43853 non-null  str
 10  Time_Order_picked            45584 non-null  str
 11  Weather_conditions           44968 non-null  str
 12  Road_traffic_density         44983 non-null  str
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  str
 15  Type_of_vehicle              45584 non-null  str
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  str
 18  City                         44384 non-null  str
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 7.0 MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,45584,45584,0xcdcd,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_person_ID,45584,1320,JAPRES11DEL02,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery_person_Age,43730.0,NaN,NaN,NaN,29.566911,5.815064,15.0,25.0,30.0,35.0,50.0
Delivery_person_Ratings,43676.0,NaN,NaN,NaN,4.633774,0.334744,1.0,4.5,4.7,4.9,6.0
Restaurant_latitude,45584.0,NaN,NaN,NaN,17.017948,8.185674,-30.905562,12.933284,18.55144,22.728163,30.914057
Restaurant_longitude,45584.0,NaN,NaN,NaN,70.229684,22.885575,-88.366217,73.17,75.897963,78.044095,88.433452
Delivery_location_latitude,45584.0,NaN,NaN,NaN,17.46548,7.335562,0.01,12.988453,18.633934,22.785049,31.054057
Delivery_location_longitude,45584.0,NaN,NaN,NaN,70.844161,21.120578,0.01,73.28,76.002574,78.107044,88.563452
Order_Date,45584,44,15-03-2022,1192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_Orderd,43853,176,21:55,461,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_Order_picked,45584,193,21:30,495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weather_conditions,44968,6,Fog,7653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Road_traffic_density,44983,4,Low,15476,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle_condition,45584.0,NaN,NaN,NaN,1.023385,0.839055,0.0,0.0,1.0,2.0,3.0
Type_of_order,45584,4,Snack,11530,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type_of_vehicle,45584,4,motorcycle,26429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
multiple_deliveries,44591.0,NaN,NaN,NaN,0.744635,0.57251,0.0,0.0,1.0,1.0,3.0
Festival,45356,2,No,44460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,44384,3,Metropolitian,34087,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time_taken (min),45584.0,NaN,NaN,NaN,26.293963,9.384298,10.0,19.0,26.0,32.0,54.0

In [17]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [18]:
# Missing value dijadikan frame
missval = (
    df.isna()
    .sum()
    .to_frame("missing_count")
)

missval['missing_pct'] = (missval['missing_count'] / len(df) * 100)

missval.sort_values('missing_pct', ascending=False)

                             missing_count  missing_pct
Delivery_person_Ratings               1908     4.185679
Delivery_person_Age                   1854     4.067217
Time_Orderd                           1731     3.797385
City                                  1200     2.632503
multiple_deliveries                    993     2.178396
Weather_conditions                     616     1.351351
Road_traffic_density                   601     1.318445
Festival                               228     0.500176
ID                                       0     0.000000
Delivery_person_ID                       0     0.000000
Restaurant_latitude                      0     0.000000
Restaurant_longitude                     0     0.000000
Time_Order_picked                        0     0.000000
Order_Date                               0     0.000000
Delivery_location_latitude               0     0.000000
Delivery_location_longitude              0     0.000000
Type_of_vehicle                          0     0.000000
Type_of_order                            0     0.000000
Vehicle_condition                        0     0.000000
Time_taken (min)                         0     0.000000

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.dtypes

ID                                 str
Delivery_person_ID                 str
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                         str
Time_Orderd                        str
Time_Order_picked                  str
Weather_conditions                 str
Road_traffic_density               str
Vehicle_condition                int64
Type_of_order                      str
Type_of_vehicle                    str
multiple_deliveries            float64
Festival                           str
City                               str
Time_taken (min)                 int64
dtype: object